/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as StressRouteImport } from "./routes/stress";
import { Route as StatsRouteImport } from "./routes/stats";
import { Route as SleepRouteImport } from "./routes/sleep";
import { Route as NutritionRouteImport } from "./routes/nutrition";
import { Route as MusclesRouteImport } from "./routes/muscles";
import { Route as IndexRouteImport } from "./routes/index";

const StressRoute = StressRouteImport.update({
  id: "/stress",
  path: "/stress",
  getParentRoute: () => rootRouteImport,
} as any);
const StatsRoute = StatsRouteImport.update({
  id: "/stats",
  path: "/stats",
  getParentRoute: () => rootRouteImport,
} as any);
const SleepRoute = SleepRouteImport.update({
  id: "/sleep",
  path: "/sleep",
  getParentRoute: () => rootRouteImport,
} as any);
const NutritionRoute = NutritionRouteImport.update({
  id: "/nutrition",
  path: "/nutrition",
  getParentRoute: () => rootRouteImport,
} as any);
const MusclesRoute = MusclesRouteImport.update({
  id: "/muscles",
  path: "/muscles",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/muscles": typeof MusclesRoute;
  "/nutrition": typeof NutritionRoute;
  "/sleep": typeof SleepRoute;
  "/stats": typeof StatsRoute;
  "/stress": typeof StressRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/muscles": typeof MusclesRoute;
  "/nutrition": typeof NutritionRoute;
  "/sleep": typeof SleepRoute;
  "/stats": typeof StatsRoute;
  "/stress": typeof StressRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/muscles": typeof MusclesRoute;
  "/nutrition": typeof NutritionRoute;
  "/sleep": typeof SleepRoute;
  "/stats": typeof StatsRoute;
  "/stress": typeof StressRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/muscles" | "/nutrition" | "/sleep" | "/stats" | "/stress";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/muscles" | "/nutrition" | "/sleep" | "/stats" | "/stress";
  id:
    | "__root__"
    | "/"
    | "/muscles"
    | "/nutrition"
    | "/sleep"
    | "/stats"
    | "/stress";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  MusclesRoute: typeof MusclesRoute;
  NutritionRoute: typeof NutritionRoute;
  SleepRoute: typeof SleepRoute;
  StatsRoute: typeof StatsRoute;
  StressRoute: typeof StressRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/stress": {
      id: "/stress";
      path: "/stress";
      fullPath: "/stress";
      preLoaderRoute: typeof StressRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/stats": {
      id: "/stats";
      path: "/stats";
      fullPath: "/stats";
      preLoaderRoute: typeof StatsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sleep": {
      id: "/sleep";
      path: "/sleep";
      fullPath: "/sleep";
      preLoaderRoute: typeof SleepRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/nutrition": {
      id: "/nutrition";
      path: "/nutrition";
      fullPath: "/nutrition";
      preLoaderRoute: typeof NutritionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/muscles": {
      id: "/muscles";
      path: "/muscles";
      fullPath: "/muscles";
      preLoaderRoute: typeof MusclesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MusclesRoute: MusclesRoute,
  NutritionRoute: NutritionRoute,
  SleepRoute: SleepRoute,
  StatsRoute: StatsRoute,
  StressRoute: StressRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
